<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Louis THIDET">
<meta name="dcterms.date" content="2024-01-08">

<title>Analyzing and Visualizing Ridership Patterns in Île-de-France Rail Network</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="analysis_report_files/libs/clipboard/clipboard.min.js"></script>
<script src="analysis_report_files/libs/quarto-html/quarto.js"></script>
<script src="analysis_report_files/libs/quarto-html/popper.min.js"></script>
<script src="analysis_report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="analysis_report_files/libs/quarto-html/anchor.min.js"></script>
<link href="analysis_report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="analysis_report_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="analysis_report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="analysis_report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="analysis_report_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data-analysis" id="toc-data-analysis" class="nav-link" data-scroll-target="#data-analysis">Data Analysis</a>
  <ul class="collapse">
  <li><a href="#data-description" id="toc-data-description" class="nav-link" data-scroll-target="#data-description">0. Data Description</a></li>
  <li><a href="#data-collection-and-cleaning" id="toc-data-collection-and-cleaning" class="nav-link" data-scroll-target="#data-collection-and-cleaning">1. Data Collection and Cleaning</a></li>
  <li><a href="#exploratory-data-analysis-eda" id="toc-exploratory-data-analysis-eda" class="nav-link" data-scroll-target="#exploratory-data-analysis-eda">2. Exploratory Data Analysis (EDA)</a></li>
  <li><a href="#comparison-with-norms" id="toc-comparison-with-norms" class="nav-link" data-scroll-target="#comparison-with-norms">3. Comparison with Norms</a></li>
  <li><a href="#analysis-conclusion" id="toc-analysis-conclusion" class="nav-link" data-scroll-target="#analysis-conclusion">4. Analysis Conclusion</a></li>
  </ul></li>
  <li><a href="#shiny-application" id="toc-shiny-application" class="nav-link" data-scroll-target="#shiny-application">Shiny Application</a></li>
  <li><a href="#limits" id="toc-limits" class="nav-link" data-scroll-target="#limits">Limits</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analyzing and Visualizing Ridership Patterns in Île-de-France Rail Network</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Louis THIDET </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 8, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This document describes the process of building a Shiny application to visualize the evolution of railway stations ridership in the Île-de-France region and brings an analysis which shows what an average ridership in a week is. It helps to discern traffic variations and distinguishing normal weeks and holiday periods. To make it, we used several datasets from the STIF Open Data portal :</p>
<ul>
<li><a href="https://data.iledefrance-mobilites.fr/explore/dataset/validations-reseau-ferre-nombre-validations-par-jour-1er-semestre/information/">validation per day and stop point first semester of 2023</a></li>
<li><a href="https://data.iledefrance-mobilites.fr/explore/dataset/histo-validations-reseau-ferre/information/">validation per day and stop point 2015 - 2022</a></li>
<li><a href="https://data.iledefrance-mobilites.fr/explore/dataset/zones-d-arrets/information/?disjunctive.zdatype">stops i.e “Zone d’arrêt” locations</a>, and it’s spatial data file: <a href="https://eu.ftp.opendatasoft.com/stif/Reflex/REF_ZdA.zip" class="uri">https://eu.ftp.opendatasoft.com/stif/Reflex/REF_ZdA.zip</a></li>
</ul>
<p>You can access to the Shiny online application <a href="https://louis-thidet.shinyapps.io/thidet_ridership_patterns_idf/">here</a></p>
</section>
<section id="data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="data-analysis">Data Analysis</h2>
<section id="data-description" class="level3">
<h3 class="anchored" data-anchor-id="data-description">0. Data Description</h3>
<ul>
<li><p>validation per day and stop point files:</p>
<ul>
<li>JOUR: date</li>
<li>CODE_STIF_TRNS: carrier’s Stif code</li>
<li>CODE_STIF_RES: Network Stif code</li>
<li>CODE_STIF_ARRET: stop Stif code</li>
<li>LIBELLE_ARRET: name of a stop on a line (example: Alesia)</li>
<li>ID_REFA_LDA: STIF reference stop identifier</li>
<li>CATEGORIE_TITRE: ticket category (e.g.&nbsp;Navigo, Imagine R)</li>
<li>NB_VALD: number of validations carried out on a given date on the network (for a given ticket)</li>
</ul></li>
</ul>
</section>
<section id="data-collection-and-cleaning" class="level3">
<h3 class="anchored" data-anchor-id="data-collection-and-cleaning">1. Data Collection and Cleaning</h3>
<p>First, we created a script called get_data.R, which uses the httr package to quickly download all the data needed to build the project. This script is useful because it allows us to quickly retrieve data if the site hosting it has updated it, or if it has been deleted from our computer.</p>
<p>Then we made a script called load_data.R. It loads the downloaded data that have been downloaded with get_data.R, then clean them and aggregate them. It produces three dataframes: stop_area_locations, vpd_combined, which is a combination of every ridership data file downloaded, and vpd_aggregated_per_day_and_stop_area, which is an aggregated version per day and stop area (“zone d’arrêt”) of vpd_combined. As load_data.R can take some time to run, at the end of the script the tables created are saved in .rds files, so that they can be loaded more quickly later.</p>
<p>Commentaries are provided in the scripts for more details.</p>
</section>
<section id="exploratory-data-analysis-eda" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-data-analysis-eda">2. Exploratory Data Analysis (EDA)</h3>
<p>We can identify the overall trends and patterns in ridership of Île-de-France’s railway stations by creating a line chart that shows for each day in a year the number of validations. To do that, we won’t take the latest data available, which are the one of 2023, because the data of 2023’s second semester yet are not available. The chart that we will create will take the data of 2018. We will also use these data for the rest of the analysis. We avoid choosing years like 2020 or 2021 because the ridership probably was affected by COVID19’s pandemic.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Loading aggregated data per days and stop area</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>vpd_aggregated_per_day_and_stop_area <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"data/vpd_aggregated_per_day_and_stop_area.rds"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Getting aggregated data per days exclusively</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>vpd_aggregated_per_day <span class="ot">&lt;-</span> vpd_aggregated_per_day_and_stop_area <span class="sc">%&gt;%</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(JOUR) <span class="sc">%&gt;%</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">NB_VALD =</span> <span class="fu">sum</span>(NB_VALD)) <span class="sc">%&gt;%</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtering data to 2018</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>vpd_aggregated_per_day <span class="ot">&lt;-</span> vpd_aggregated_per_day <span class="sc">%&gt;%</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(JOUR <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">"2018-01-01"</span>) <span class="sc">&amp;</span> JOUR <span class="sc">&lt;=</span> <span class="fu">as.Date</span>(<span class="st">"2018-12-31"</span>))</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Defining holiday periods</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>holiday_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">start_date =</span> <span class="fu">as.Date</span>(<span class="fu">c</span>(<span class="st">"2017-12-23"</span>, <span class="st">"2018-02-17"</span>, <span class="st">"2018-04-14"</span>, <span class="st">"2018-05-10"</span>,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>                         <span class="st">"2018-07-07"</span>, <span class="st">"2018-10-20"</span>, <span class="st">"2018-12-22"</span>)),</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">end_date =</span> <span class="fu">as.Date</span>(<span class="fu">c</span>(<span class="st">"2018-01-08"</span>, <span class="st">"2018-03-05"</span>, <span class="st">"2018-04-30"</span>, <span class="st">"2018-05-16"</span>,</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"2018-09-02"</span>, <span class="st">"2018-11-05"</span>, <span class="st">"2019-01-07"</span>)),</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">label =</span> <span class="fu">c</span>(<span class="st">"Christmas 2017"</span>, <span class="st">"Winter 2018"</span>, <span class="st">"Spring 2018"</span>, <span class="st">"Ascension 2018"</span>,</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Great Holidays 2018"</span>, <span class="st">"All Saints' Day 2018"</span>, <span class="st">"Christmas 2018"</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating plot</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(vpd_aggregated_per_day, <span class="fu">aes</span>(<span class="at">x =</span> JOUR, <span class="at">y =</span> NB_VALD)) <span class="sc">+</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> mean, <span class="at">color =</span> <span class="st">'grey'</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Vertical lines to display holiday periods</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">data =</span> holiday_data, <span class="fu">aes</span>(<span class="at">xintercept =</span> start_date, <span class="at">color =</span> label), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">data =</span> holiday_data, <span class="fu">aes</span>(<span class="at">xintercept =</span> end_date, <span class="at">color =</span> label), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Horizontal line to display a threshold</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">6000000</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Theme</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> <span class="cf">function</span>(x) <span class="fu">format</span>(x, <span class="at">scientific =</span> <span class="cn">FALSE</span>, <span class="at">trim =</span> <span class="cn">TRUE</span>)) <span class="sc">+</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Titles</span></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Number of Validations in 2017"</span>,</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Months"</span>,</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of Validations"</span></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">color =</span> <span class="fu">guide_legend</span>(<span class="at">title =</span> <span class="st">"Holidays"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="analysis_report_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid" width="960"></p>
</div>
</div>
<p>In our chart, we have highlighted every holiday in 2018. The first observation to do is that during the holiday periods, the railway stations are much less crowded as the rest of the year. We can easily notice too that the ridership increases again at the end of holiday periods. This is especially true for the Great Holidays of Summer. The second observation is that each week there is a fall in the number of validations. It happens in the weekend, and particularly on Sunday.</p>
<p>We can also check how are the trends in a particular stop area. For example, Saint-Lazare.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter data for the specified date range</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>filtered_data <span class="ot">&lt;-</span> vpd_aggregated_per_day_and_stop_area <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(JOUR <span class="sc">&gt;=</span> <span class="fu">as.Date</span>(<span class="st">"2018-01-01"</span>) <span class="sc">&amp;</span> JOUR <span class="sc">&lt;=</span> <span class="fu">as.Date</span>(<span class="st">"2018-12-31"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ID_REFA_LDA <span class="sc">==</span> <span class="st">"71370"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating plot</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(filtered_data, <span class="fu">aes</span>(<span class="at">x =</span> JOUR, <span class="at">y =</span> NB_VALD)) <span class="sc">+</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">stat =</span> <span class="st">"summary"</span>, <span class="at">fun =</span> mean, <span class="at">color =</span> <span class="st">'grey'</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Vertical lines to display holiday periods</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">data =</span> holiday_data, <span class="fu">aes</span>(<span class="at">xintercept =</span> start_date, <span class="at">color =</span> label), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">data =</span> holiday_data, <span class="fu">aes</span>(<span class="at">xintercept =</span> end_date, <span class="at">color =</span> label), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Horizontal line to display a threshold</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">35000</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Theme</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> <span class="cf">function</span>(x) <span class="fu">format</span>(x, <span class="at">scientific =</span> <span class="cn">FALSE</span>, <span class="at">trim =</span> <span class="cn">TRUE</span>)) <span class="sc">+</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Titles</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Number of Validations in 2017"</span>,</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Months"</span>,</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of Validations"</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">color =</span> <span class="fu">guide_legend</span>(<span class="at">title =</span> <span class="st">"Holidays"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="analysis_report_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="960"></p>
</div>
</div>
<p>The difference between holiday and non-holiday periods is getting very blurry there, thought we still see that validation per day falls on weekends. Saint-Lazare is one of the biggest stop area in both Paris and Île-de-France, and it doesn’t represent an overall trend.</p>
<p>For a global approach of seasons and monthly trends, it is relevant to make a box plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(vpd_aggregated_per_day, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.factor</span>(<span class="fu">month</span>(JOUR)), <span class="at">y =</span> NB_VALD)) <span class="sc">+</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Seasons and Monthly Trends"</span>, <span class="at">x =</span> <span class="st">"Months"</span>, <span class="at">y =</span> <span class="st">"Number of validations"</span>) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> <span class="cf">function</span>(x) <span class="fu">format</span>(x, <span class="at">scientific =</span> <span class="cn">FALSE</span>, <span class="at">trim =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="analysis_report_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The box plot provides a visual summary of the distribution of validations per day for each month. The fact the mean of almost each month is very close to the upper quartile is caused by the fact the distribution of each month is stretched toward high values: there is a high amount of validations for the most of the days, and only a few days with a low amount (the weekends). We can verify it with a density plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtering data on March</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>selected_month <span class="ot">&lt;-</span> <span class="dv">3</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>filtered_data <span class="ot">&lt;-</span> vpd_aggregated_per_day <span class="sc">%&gt;%</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">month</span>(JOUR) <span class="sc">==</span> selected_month)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Density plot</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(filtered_data, <span class="fu">aes</span>(<span class="at">x =</span> NB_VALD)) <span class="sc">+</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">fill =</span> <span class="st">"blue"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">"Density Plot of Daily Validation Counts for March"</span>),</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Number of Validations"</span>,</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Density"</span>) <span class="sc">+</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> <span class="cf">function</span>(x) <span class="fu">format</span>(x, <span class="at">scientific =</span> <span class="cn">FALSE</span>, <span class="at">trim =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="analysis_report_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The density plot above (showing March) shows that most of the days in a month have a high number of validations.</p>
<p>Finally, we can observe the trends not of a year or a month, but of the average week, on a barplot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating average week</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>average_week <span class="ot">&lt;-</span> vpd_aggregated_per_day <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="at">weekday =</span> <span class="fu">weekdays</span>(JOUR)) <span class="sc">%&gt;%</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">NB_VALD =</span> <span class="fu">mean</span>(NB_VALD))</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Ploting the average week as a bar plot</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(average_week, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(weekday, <span class="sc">-</span>NB_VALD), <span class="at">y =</span> NB_VALD)) <span class="sc">+</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Comparaison avec la semaine normale"</span>,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Jour de la semaine"</span>,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Moyenne de validations"</span>) <span class="sc">+</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> <span class="cf">function</span>(x) <span class="fu">format</span>(x, <span class="at">scientific =</span> <span class="cn">FALSE</span>, <span class="at">trim =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="analysis_report_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>What we did here is calculating the mean number of validation for each day of the week in the year 2018.</p>
<p>It was already visible on the line chart, that there was way less validations on Saturday and Sunday, but we can more appreciate it more easily there. And we also find out that as the days pass in the week, there is more validations, till Friday.</p>
</section>
<section id="comparison-with-norms" class="level3">
<h3 class="anchored" data-anchor-id="comparison-with-norms">3. Comparison with Norms</h3>
<p>We have already calculated the average week when doing the bar plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reference week mean validation per day</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>reference_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(average_week<span class="sc">$</span>NB_VALD)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(average_week<span class="sc">$</span>NB_VALD)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4586093</code></pre>
</div>
</div>
<p>The average number of validations per day on the defined reference week is 4586093.</p>
<p>We can compare it with a random week which is outside the holiday periods. 2018-12-03 to 2018-12-09 for example. We will calculate the difference between the average number of validations in the average week and this other week.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Random week mean validation per day</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>another_week <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">as.Date</span>(<span class="st">"2018-12-03"</span>), <span class="fu">as.Date</span>(<span class="st">"2018-12-09"</span>), <span class="at">by =</span> <span class="st">"day"</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Getting the mean</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>week_data <span class="ot">&lt;-</span> vpd_aggregated_per_day <span class="sc">%&gt;%</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(JOUR <span class="sc">%in%</span> another_week) <span class="sc">%&gt;%</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(JOUR) <span class="sc">%&gt;%</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(NB_VALD)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(week_data<span class="sc">$</span>NB_VALD) <span class="sc">-</span> reference_mean <span class="co"># Difference with reference week</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 531194</code></pre>
</div>
</div>
<p>The average number of validations per day on the random week is 5117287, and the difference between the average week and this random week outside of the holiday periods is 531194. This means there is a bit more validations during the Ascension week than in the average week.</p>
<p>Now we will compare the average week with the week of Ascension.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Long Weekend of Ascension 2018 mean validation per day</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>ascension2018 <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">as.Date</span>(<span class="st">"2018-05-10"</span>), <span class="fu">as.Date</span>(<span class="st">"2018-05-16"</span>), <span class="at">by =</span> <span class="st">"day"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Getting the mean</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>holiday_data <span class="ot">&lt;-</span> vpd_aggregated_per_day <span class="sc">%&gt;%</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(JOUR <span class="sc">%in%</span> ascension2018) <span class="sc">%&gt;%</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(JOUR) <span class="sc">%&gt;%</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(NB_VALD)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(holiday_data<span class="sc">$</span>NB_VALD) <span class="sc">-</span> reference_mean <span class="co"># Difference with reference week</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -506248.7</code></pre>
</div>
</div>
<p>The average number of validations per day on the Ascension week is 4079845, but the difference between the average week and this Ascension week is -506248.7. This means there is less validations during the Ascension week than in the average week. To be sure that this is meaningful, we will do the difference between the average week’s mean validation per day and the mean validation per day of all holiday period.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Defining all holiday periods</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>holidays <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">christmas2017 =</span> <span class="fu">seq</span>(<span class="fu">as.Date</span>(<span class="st">"2017-12-23"</span>), <span class="fu">as.Date</span>(<span class="st">"2018-01-08"</span>), <span class="at">by =</span> <span class="st">"day"</span>),</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">winter2018 =</span> <span class="fu">seq</span>(<span class="fu">as.Date</span>(<span class="st">"2018-02-17"</span>), <span class="fu">as.Date</span>(<span class="st">"2018-03-05"</span>), <span class="at">by =</span> <span class="st">"day"</span>),</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">spring2018 =</span> <span class="fu">seq</span>(<span class="fu">as.Date</span>(<span class="st">"2018-04-14"</span>), <span class="fu">as.Date</span>(<span class="st">"2018-04-30"</span>), <span class="at">by =</span> <span class="st">"day"</span>),</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">ascension2018 =</span> <span class="fu">seq</span>(<span class="fu">as.Date</span>(<span class="st">"2018-05-10"</span>), <span class="fu">as.Date</span>(<span class="st">"2018-05-16"</span>), <span class="at">by =</span> <span class="st">"day"</span>),</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">great_holiday2018 =</span> <span class="fu">seq</span>(<span class="fu">as.Date</span>(<span class="st">"2018-07-07"</span>), <span class="fu">as.Date</span>(<span class="st">"2018-09-02"</span>), <span class="at">by =</span> <span class="st">"day"</span>),</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">all_saints_day2018 =</span> <span class="fu">seq</span>(<span class="fu">as.Date</span>(<span class="st">"2018-10-20"</span>), <span class="fu">as.Date</span>(<span class="st">"2018-11-05"</span>), <span class="at">by =</span> <span class="st">"day"</span>),</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">christmas2018 =</span> <span class="fu">seq</span>(<span class="fu">as.Date</span>(<span class="st">"2018-12-22"</span>), <span class="fu">as.Date</span>(<span class="st">"2019-01-07"</span>), <span class="at">by =</span> <span class="st">"day"</span>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Getting the mean for each holiday period</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>average_diffs <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="fu">length</span>(holidays))</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(holidays)) {</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>  holiday_data <span class="ot">&lt;-</span> vpd_aggregated_per_day <span class="sc">%&gt;%</span></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(JOUR <span class="sc">%in%</span> holidays[[i]]) <span class="sc">%&gt;%</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(JOUR) <span class="sc">%&gt;%</span></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(NB_VALD)</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>  average_diffs[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(holiday_data<span class="sc">$</span>NB_VALD) <span class="sc">-</span> reference_mean</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Mean of the means</span></span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(average_diffs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -747458</code></pre>
</div>
</div>
<p>We have calculated the difference between the average week’s mean validation per day and the mean validation per day of each holiday, before making the mean of the results. The value obtained is -747458. This means there is 747458 more validations on an average week than during holiday periods. To confirm these results are significant, we’re gonna use a statistical test named Student’s t-test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(average_diffs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  average_diffs
t = -3.4146, df = 6, p-value = 0.01424
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 -1283082.0  -211833.9
sample estimates:
mean of x 
  -747458 </code></pre>
</div>
</div>
<p>We obtained a p-value of 0.01424, which means the results are likely 95% significant.</p>
</section>
<section id="analysis-conclusion" class="level3">
<h3 class="anchored" data-anchor-id="analysis-conclusion">4. Analysis Conclusion</h3>
<p>Ridership on the Île-de-France railway stations is organized with two phases: holiday periods and non-holiday periods. There are a large number of passengers on the network every day, but this number drops sharply at weekends, to more than halve on Sundays. But the overall trends and patters don’t necessarily follow the trends and patterns of particulars stop areas, which can vary greatly.</p>
</section>
</section>
<section id="shiny-application" class="level2">
<h2 class="anchored" data-anchor-id="shiny-application">Shiny Application</h2>
<p>The Shiny application we’ve created can display several periods of information between the different stations contained in the data we use. There are two types of period in this application: weeks and custom periods. When using the week mode, a bar plot is displayed for each day of the week, while the custom period mode displays a line chart whose values correspond to days of a year, and on which you can display all the weeks you wish.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/screenshot_1.PNG" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Application look at startup</figcaption>
</figure>
</div>
<p>The application offers the option of displaying either data from one stop area, or data from two stop area at once. In the latter case, two graphs are superimposed (in the case of week mode, the day bars are placed side by side, otherwise it would be difficult to read), allowing you to appreciate the difference between the information consulted. Data configured as period 1 are displayed in red, while those configured as period 2 are shown in purple. The application also displays a blue box containing the key data of the data displayed on the screen. This key data is the average validation per day between all the data displayed.</p>
<p>Here’s a detailed description of the week mode functionalities. For each of the two stop areas you wish to display and compare (you can also choose to display only one of them. And note that you can select the Average Stop Area, the one whose values are the average of all the existing stop areas), you choose the year of the week to be displayed, then you can display either the average week of the stop area, or the average week of the stop area’s one-year holiday period, or the average week between several selected weeks (For example, if I’ve set the year 2022, I can display the average week between weeks 10 to 23 of 2022. In this and previous cases, what the application does each time is calculating an average week between several weeks), or a particular week (such as week 10 of 2022).</p>
<p><img src="img/screenshot_2.PNG" class="img-fluid" alt="Comparing the stop areas of Argentine and Alesia"></p>
<p>The custom period mode allows you to select a year for both stop areas, as well as the period to be observed. It selects this period in weeks. The data is then displayed as a line chart. For each stop area configured, a line corresponds to the average number of validations per day over the period observed. But there are also vertical lines, showing the beginning and end of holiday periods.</p>
<p>But that’s not all. In fact, the application doesn’t just compare information between two stop areas. It can display information not only from the stop areas that we have chosen (Then, happens what we described earlier), but also from the stop areas around the stop areas chosen. This is why it has an input called “Range of Close Stop Area”, which configures in meters the range within which the stop areas around the selected stop areas will be considered. When the Information to Display input is set to “Close Stop Area”, not only the selected stop areas are put into the plots, but also the stop areas around them. The application averages the data from these stop areas before displaying them. This feature is the reason why the application includes a map. It shows which stop areas are located around the selected stop areas, and where the selected stop areas are located.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/screenshot_3.PNG" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">While the ridership is very similar between Antony and Alesia, we see the ridership is way more dense around Alesia</figcaption>
</figure>
</div>
<p>Finally, the application also offers secondary functionalities. Users can, if they wish, consult the data used directly from the application. It contains a Data Tables tab, which displays the validations per day for each date and stop area (Not in online version, because it makes the application out of memory), as well as the data displayed on the plots configured.</p>
<p>In short, with its graphs, the application makes it possible to appreciate trends and developments on a local and individual level, by consulting information from just one or two stop area, but it also makes it possible to appreciate them in a more global way, via the possibility of obtaining data on an area around a given stop area and the display of data from the Average Stop Area.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/screenshot_4.PNG" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Checking the data</figcaption>
</figure>
</div>
<p>Note: If one week is displayed but the other is not, this means that the week not displayed has no data available for the selected parameters.</p>
</section>
<section id="limits" class="level2">
<h2 class="anchored" data-anchor-id="limits">Limits</h2>
<ul>
<li>We had the idea of allowing the user to display a smooth map, since it would have been probably good to show the data in an overall way. But we left this idea, because of our lack of time.</li>
<li>The applications takes several seconds to start (like 10 seconds) because of the loading of the stop areas into the stop area selection inputs.</li>
<li>The validation per day data sometimes have the same station wrote with wrong name. It makes unnecessary duplicates in the inputs to choose the stop areas and we didn’t find a good way to get rid of them without removing true values, except the manual way.</li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>